version: '3.8'

services:
  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "80:80"
    depends_on:
      - springboot-app

  springboot-app:
    build:
      context: ./springboot-app
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "8181:8181"

networks:
  default:
    driver: bridge
